### ISSUE TITLE
Shader issue on Linux

### ISSUE THREAD

**Issue by remram44** [ViDA-NYU/TaxiVis#1]
I built TaxiVis on Linux, everything seems to work except the taxis are not rendered on the map. Terminal shows:

```
grouop plots 0
QGLShader::compile(Vertex): 0:2(12): warning: extension `GL_EXT_gpu_shader4' unsupported in vertex shader
0:16(17): error: `gl_VertexID' undeclared
0:16(17): error: operands to relational operators must be scalar and numeric
0:16(17): error: condition of `?:' must be scalar boolean

QGLShader: could not create shader 
Initializing OpenGL...
Finished loading!
```

**Comment by nivan** [comment]
That is weird. I pushed a version of code that should remove this warning, although I believe this should not cause the points to disappear.
Are you using the correct time interval for the points?

**Comment by remram44** [comment]
I now only get:

```
grouop plots 0
QGLShader: could not create shader
```

The points still don't show up. I think the configuration is right, I have non-zero data in the line plot.

![taxivis](https://cloud.githubusercontent.com/assets/426784/12312228/af5c9d0c-ba2b-11e5-9cdd-4ac7a854ee3e.png)

**Comment by nivan** [comment]
Could you tell me which data are you using for this so I can try to check what is going on?

**Comment by remram44** [comment]
I'm using the default data from this repository (sample_merged_1.kdtrip).

**Comment by nivan** [comment]
That is weird. In my Linux machine I get 
![screenshot from 2016-01-14 02 23 14](https://cloud.githubusercontent.com/assets/469805/12312366/0fc68f46-ba1c-11e5-8a2e-cfc12f7704fd.png)

I just cloned the repository and compiled it.

**Comment by julianafreire** [comment]
I had the same problem as Remi in some of the early MacOS versions. Huy was able to fix that. But I don't remember what the problem was...

**Comment by nivan** [comment]
Huy,
Do you remember what was the problem?

**Comment by nivan** [comment]
Remi,

Can you try to pull the last commit I made and tell me if it helps?
The trip location layer was using immediate mode rendering, I just
set it to use VBO for now.

**Comment by remram44** [comment]
No change.

I see the dots for a second before the map loads, as if it was rendered on top of them.

I also just found out that setting `LIBGL_ALWAYS_SOFTWARE=1` fixes it (though "could not create shader" still appears in the log).
